# -*- coding: utf-8 -*-
"""letter_rec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ri-2Xn9xEfpclub5fGwq6quYK1WHzkct
"""

!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

!mkdir drive
!google-drive-ocamlfuse drive

import os 
os.chdir("/content/drive/Colab_Notebooks/11december/letter")
!pwd

import cv2 as cv
from matplotlib import pyplot as plt
from PIL import Image

#this method serves getting all images in specific folder when it is called.
def getImages(path):

  temp_arr = []   #saving images array
  name_arr= []    #saving images name
  path = path     #folder directory

  #get images with some formats from specific folder 
  valid_images = [".jpg",".gif",".jpeg",".png"]
  for f in os.listdir(path):
    ext = os.path.splitext(f)[1]
    if ext.lower() not in valid_images:
      continue

    #with the help of opencv lib
    #getting all images as array format from path
    temp_arr.append(cv.imread(os.path.join(path,f)))    

    #get raw image name from folder path with image name 
    #/content/drive/Colab_Notebooks/11december/letter/pic/testImages/x.jpg
    temp_text = str(os.path.join(path,f))
    img_name = temp_text.split('/')
    img_name = img_name[(len(temp_text.split('/'))-1)] 
    #x.jpg

    img_name_wo = img_name.split('.')
    img_name_wo = img_name[0]  
    #x

    #saving all images name into array
    name_arr.append(img_name_wo)

  return temp_arr,name_arr    #return image array and image name

#go test folder and get test images
path_test ='/content/drive/Colab_Notebooks/11december/letter/pic/testImages/'
test_arr , test_names = getImages(path_test)

#go original image folder and get images
path_chr = '/content/drive/Colab_Notebooks/11december/letter/pic/letterImages/'
chr_arr, chr_names = getImages(path_chr)

#for loop iteration
test_count = len(test_names)
chr_count = len(chr_names)

for i in range(test_count):
  for j in range(chr_count):

    comparison = test_arr[i] == chr_arr[j]    #compare images' pixels
    equality = comparison.all()               #if the same, return true

    if(equality == True):                     #test image matched with one of orjinal image          
      
      #plotting
      plt.subplot(1,test_count,i+1)         
      plt.imshow(test_arr[i]),
      plt.title(chr_names[j]), plt.xticks([]), plt.yticks([])     #without x&y axis scale
      plt.tight_layout()

#saving images
plt.suptitle('Character Detection')
plt.savefig('/content/drive/Colab_Notebooks/11december/letter/pic/'+'conversion.jpg')
plt.show()

im = cv.imread('/content/drive/Colab_Notebooks/11december/letter/pic/conversion.jpg')
plt.xticks([]), plt.yticks([])
plt.imshow(im)